// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type UprobeHTTPHttpEvent struct {
	_        structs.HostLayout
	Pid      uint64
	Method   [64]int8
	Scheme   [64]int8
	Host     [64]int8
	Path     [64]int8
	Query    [64]int8
	Nheaders uint64
	Keys     [16][64]int8
	Vals     [16][512]int8
}

type UprobeHTTPOffTableT struct {
	_             structs.HostLayout
	RequestMethod uint64
	RequestUrl    uint64
	UrlScheme     uint64
	UrlHost       uint64
	UrlPath       uint64
	UrlRawquery   uint64
	RequestHeader uint64
	SwissTables   uint64
}

// LoadUprobeHTTP returns the embedded CollectionSpec for UprobeHTTP.
func LoadUprobeHTTP() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_UprobeHTTPBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load UprobeHTTP: %w", err)
	}

	return spec, err
}

// LoadUprobeHTTPObjects loads UprobeHTTP and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*UprobeHTTPObjects
//	*UprobeHTTPPrograms
//	*UprobeHTTPMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadUprobeHTTPObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadUprobeHTTP()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// UprobeHTTPSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type UprobeHTTPSpecs struct {
	UprobeHTTPProgramSpecs
	UprobeHTTPMapSpecs
	UprobeHTTPVariableSpecs
}

// UprobeHTTPProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type UprobeHTTPProgramSpecs struct {
	HandleUprobe *ebpf.ProgramSpec `ebpf:"handle_uprobe"`
}

// UprobeHTTPMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type UprobeHTTPMapSpecs struct {
	EventScratchMap *ebpf.MapSpec `ebpf:"event_scratch_map"`
	Events          *ebpf.MapSpec `ebpf:"events"`
	GoOffsetsMap    *ebpf.MapSpec `ebpf:"go_offsets_map"`
}

// UprobeHTTPVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type UprobeHTTPVariableSpecs struct {
}

// UprobeHTTPObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadUprobeHTTPObjects or ebpf.CollectionSpec.LoadAndAssign.
type UprobeHTTPObjects struct {
	UprobeHTTPPrograms
	UprobeHTTPMaps
	UprobeHTTPVariables
}

func (o *UprobeHTTPObjects) Close() error {
	return _UprobeHTTPClose(
		&o.UprobeHTTPPrograms,
		&o.UprobeHTTPMaps,
	)
}

// UprobeHTTPMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadUprobeHTTPObjects or ebpf.CollectionSpec.LoadAndAssign.
type UprobeHTTPMaps struct {
	EventScratchMap *ebpf.Map `ebpf:"event_scratch_map"`
	Events          *ebpf.Map `ebpf:"events"`
	GoOffsetsMap    *ebpf.Map `ebpf:"go_offsets_map"`
}

func (m *UprobeHTTPMaps) Close() error {
	return _UprobeHTTPClose(
		m.EventScratchMap,
		m.Events,
		m.GoOffsetsMap,
	)
}

// UprobeHTTPVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadUprobeHTTPObjects or ebpf.CollectionSpec.LoadAndAssign.
type UprobeHTTPVariables struct {
}

// UprobeHTTPPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadUprobeHTTPObjects or ebpf.CollectionSpec.LoadAndAssign.
type UprobeHTTPPrograms struct {
	HandleUprobe *ebpf.Program `ebpf:"handle_uprobe"`
}

func (p *UprobeHTTPPrograms) Close() error {
	return _UprobeHTTPClose(
		p.HandleUprobe,
	)
}

func _UprobeHTTPClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed uprobehttp_x86_bpfel.o
var _UprobeHTTPBytes []byte
